---
- name: Set-up covid19sim
  hosts: "{{ host | default('localhost')}}"

  tasks:

    - name: Clone ctt module, required to run simulator
      git:
        repo: https://github.com/mila-iqia/COVI-ML
        dest: ~/COVI-ML
        version: 19986f7427a7a643eb05fb41e5ed4dd113362cd6
        force: y

    - name: Use fixed requirements.txt
      copy:
        src: files/requirements.txt
        dest: ~/COVI-ML

    - name: Use fixed setup.py
      copy:
        src: files/setup.py
        dest: ~/COVI-MLx

    - name: Version of ctt module should be commit hash
      lineinfile:
        path: ~/COVI-ML/setup.py
        search_string: 'version='
        line: version='19986f7427a7a643eb05fb41e5ed4dd113362cd6',

    - name: Install ctt module
      shell: cd ~/COVI-ML && pip install -e .

    - name: Checkout a viable commit
      git:
        repo: https://github.com/QuMuLab/COVI-AgentSim
        dest: ~/COVI-AgentSim
        version: 8a8b9b5aa5ac4c13dd7220d856119e3916148622
        force: yes
        
    - name: Version of covid19sim module should be commit hash
      lineinfile:
        path: ~/COVI-AgentSim/setup.py
        search_string: 'version'
        line: version='8a8b9b5aa5ac4c13dd7220d856119e3916148622',

    - name: Install simulator 
      shell: pip install -e .
      args:
        chdir: ~/COVI-AgentSim


